-- MySQL Workbench Synchronization
-- Generated: 2026-04-27 10:14
-- Model: New Model
-- Version: 1.0
-- Project: Name of the project
-- Author: 221

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

ALTER TABLE `pr1`.`shipment` 
DROP FOREIGN KEY `book_id`;

ALTER TABLE `pr1`.`shipment` 
ADD COLUMN `shipment_id` INT(11) NOT NULL FIRST,
DROP PRIMARY KEY,
ADD PRIMARY KEY (`shipment_id`),
ADD INDEX `fk_shipment_books1_idx` (`book_id` ASC) VISIBLE;
;

ALTER TABLE `pr1`.`shipment` 
ADD CONSTRAINT `fk_shipment_books1`
  FOREIGN KEY (`book_id`)
  REFERENCES `pr1`.`books` (`book_id`)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
