CREATE EVENT event2
ON SCHEDULE EVERY 150 SECOND
STARTS CURRENT_TIMESTAMP
ENDS CURRENT_TIMESTAMP + INTERVAL 24 HOUR
ON COMPLETION PRESERVE
DO
    INSERT INTO my_event_table(eventTime, eventName)
    VALUES(CURRENT_TIMESTAMP, 'событие 2');