CREATE EVENT event1
ON SCHEDULE EVERY 10 SECOND
STARTS CURRENT_TIMESTAMP
ENDS CURRENT_TIMESTAMP + INTERVAL 5 MINUTE
ON COMPLETION PRESERVE
DO
    INSERT INTO my_event_table(eventTime, eventName)
    VALUES(CURRENT_TIMESTAMP, 'событие 1');